version: 2.1

orbs:
  architect: giantswarm/architect@2.4.2

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build-ignition-operator
          binary: ignition-operator
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-ignition-operator-to-quay
          image: "quay.io/giantswarm/ignition-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build-ignition-operator
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - hold-push-ignition-operator-to-aliyun-pr:
          type: approval
          requires:
            - go-build-ignition-operator
          # Needed to prevent job from being triggered on master branch.
          filters:
            branches:
              ignore: master

      - architect/push-to-docker:
          name: push-ignition-operator-to-aliyun-pr
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/ignition-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          # Push to Aliyun should execute for non-master branches only once manually approved.
          requires:
            - hold-push-ignition-operator-to-aliyun-pr
          # Needed to prevent job being triggered for master branch.
          filters:
            branches:
              ignore: master

      # Push to Aliyun should execute without manual approval on master.
      - architect/push-to-docker:
          name: push-ignition-operator-to-aliyun-master
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/ignition-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build-ignition-operator
          # Needed to trigger job only on merge to master.
          filters:
            branches:
              only: master

      - architect/push-to-app-catalog:
          name: push-ignition-operator-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "ignition-operator"
          requires:
            - push-ignition-operator-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: app-collection
          app_name: "ignition-operator"
          app_collection_repo: "operator-week-app-collection"
          requires:
            - push-ignition-operator-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
