apiVersion: v1
kind: Pod
metadata:
  name: k8s-api-server
  namespace: kube-system
  labels:
    k8s-app: api-server
    tier: control-plane
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  containers:
  - name: k8s-api-server
    image: {{ .Spec.Registry.Domain }}/{{ .Spec.Kubernetes.Image }}
    env:
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    command:
    - /hyperkube
    - kube-apiserver
    - --allow-privileged=true
    - --anonymous-auth=false
    - --insecure-port=0
    - --kubelet-https=true
    - --kubelet-preferred-address-types=InternalIP
    - --secure-port={{ .Spec.Kubernetes.API.SecurePort }}
    - --bind-address=0.0.0.0
    - --etcd-prefix={{ .Spec.Etcd.Prefix }}
    - --profiling=false
    - --service-account-lookup=true
    - --authorization-mode=RBAC
    - --feature-gates=TTLAfterFinished=true
    - --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,DefaultStorageClass,PersistentVolumeClaimResize,PodSecurityPolicy,Priority,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
    - --cloud-provider={{ .Spec.Kubernetes.CloudProvider }}
    - --service-cluster-ip-range={{ .Spec.Kubernetes.IPRange }}
    - --etcd-servers=https://127.0.0.1:2379
    - --etcd-cafile=/etc/kubernetes/ssl/etcd/server-ca.pem
    - --etcd-certfile=/etc/kubernetes/ssl/etcd/server-crt.pem
    - --etcd-keyfile=/etc/kubernetes/ssl/etcd/server-key.pem
    - --advertise-address=$(HOST_IP)
    - --runtime-config=api/all=true,scheduling.k8s.io/v1alpha1=true
    - --logtostderr=true
    - --tls-cert-file=/etc/kubernetes/ssl/apiserver-crt.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --client-ca-file=/etc/kubernetes/ssl/apiserver-ca.pem
    - --service-account-key-file=/etc/kubernetes/ssl/service-account-key.pem
    - --audit-log-path=/var/log/apiserver/audit.log
    - --audit-log-maxage=30
    - --audit-log-maxbackup=30
    - --audit-log-maxsize=100
    - --audit-policy-file=/etc/kubernetes/policies/audit-policy.yaml
    - --encryption-provider-config=/etc/kubernetes/encryption/k8s-encryption-config.yaml
    - --requestheader-client-ca-file=/etc/kubernetes/ssl/apiserver-ca.pem
    - --requestheader-allowed-names=aggregator,{{ .Spec.Kubernetes.API.Domain }},{{ .Spec.Kubernetes.Kubelet.Domain }}
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --proxy-client-cert-file=/etc/kubernetes/ssl/apiserver-crt.pem
    - --proxy-client-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    {{ if .Spec.Kubernetes.OIDC.Enabled -}}
    - --oidc-issuer-url={{ .Spec.Kubernetes.OIDC.IssuerURL }}
    - --oidc-client-id={{ .Spec.Kubernetes.OIDC.ClientID }}
    - --oidc-username-claim={{ .Spec.Kubernetes.OIDC.UsernameClaim }}
    - --oidc-groups-claim={{ .Spec.Kubernetes.OIDC.GroupsClaim }}
    {{ end -}}
    resources:
      requests:
        cpu: 300m
        memory: 300Mi
    livenessProbe:
      tcpSocket:
        port: {{ .Spec.Kubernetes.API.SecurePort }}
      initialDelaySeconds: 15
      timeoutSeconds: 15
    ports:
    - containerPort: {{ .Spec.Kubernetes.API.SecurePort }}
      hostPort: {{ .Spec.Kubernetes.API.SecurePort }}
      name: https
    volumeMounts:
    - mountPath: /var/log/apiserver/
      name: apiserver-log
    - mountPath: /etc/kubernetes/encryption/
      name: k8s-encryption
      readOnly: true
    - mountPath: /etc/kubernetes/manifests
      name: k8s-manifests
      readOnly: true
    - mountPath: /etc/kubernetes/policies
      name: k8s-policies
      readOnly: true
    - mountPath: /etc/kubernetes/secrets/
      name: k8s-secrets
      readOnly: true
    - mountPath: /etc/kubernetes/ssl/
      name: ssl-certs-kubernetes
      readOnly: true
  volumes:
  - hostPath:
      path: /var/log/apiserver/
    name: apiserver-log
  - hostPath:
      path: /etc/kubernetes/encryption/
    name: k8s-encryption
  - hostPath:
      path: /etc/kubernetes/manifests
    name: k8s-manifests
  - hostPath:
      path: /etc/kubernetes/policies
    name: k8s-policies
  - hostPath:
      path: /etc/kubernetes/secrets
    name: k8s-secrets
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
